GET http://localhost:8000/products/ HTTP/1.1

###

GET http://localhost:8000/user-orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY2NTU4MTg0LCJpYXQiOjE3NjY1NTc4ODQsImp0aSI6IjNjMzZmNzcyYTVlNzRhYjNiNzA2NTcxOTUwYjViNzFlIiwidXNlcl9pZCI6IjEifQ.732Fyv8i3l86DIAxi1MGT3LjKttGFTex5PRaz2qPps8


###
GET http://localhost:8000/products/2/ HTTP/1.1
###
PUT http://localhost:8000/products/2/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY2NTYwNDE1LCJpYXQiOjE3NjY1NjAxMTUsImp0aSI6IjhlM2JiMjc0NDY3OTQ2OTU5MWU1MzM4NjM3ZDAxZjI3IiwidXNlcl9pZCI6IjEifQ.anJKefhAUKT8t8zWJV8YuQsuqn-QYkpTniNcL8aJ2GQ

{
   "name": "Product_1",
   "description": "A 50-inch 4K UHD Smart TV",
   "price": "3000.99",
   "stock": 328
}

###
DELETE  http://localhost:8000/products/2/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY2NTYwNDE1LCJpYXQiOjE3NjY1NjAxMTUsImp0aSI6IjhlM2JiMjc0NDY3OTQ2OTU5MWU1MzM4NjM3ZDAxZjI3IiwidXNlcl9pZCI6IjEifQ.anJKefhAUKT8t8zWJV8YuQsuqn-QYkpTniNcL8aJ2GQ

###


POST http://localhost:8000/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY2NTU4MTg0LCJpYXQiOjE3NjY1NTc4ODQsImp0aSI6IjNjMzZmNzcyYTVlNzRhYjNiNzA2NTcxOTUwYjViNzFlIiwidXNlcl9pZCI6IjEifQ.732Fyv8i3l86DIAxi1MGT3LjKttGFTex5PRaz2qPps8

{
   "name": "Television",
   "description": "A 50-inch 4K UHD Smart TV",
   "price": "499.99",
   "stock": 30
}

###


POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "test"
}

###

POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "anshsingh25",
    "password": "test@123"
}

###

POST http://localhost:8000/api/token/refresh/ HTTP/1.1
Content-Type: application/json

{
   "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2NjY0NDk0MCwiaWF0IjoxNzY2NTU4NTQwLCJqdGkiOiI0ZGE0OGI2YmUxMzg0YjUxODllYTIxNDg3N2U3ZGJjMSIsInVzZXJfaWQiOiI0In0._EvCDegSy9yZESxh7a5DmjIDEwtbI3AOjNUZFW-4aps" 
}

###

GET http://localhost:8000/orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY2NjYxNDk4LCJpYXQiOjE3NjY2NjExOTgsImp0aSI6ImM2OWMwMzQwMTdiYTRhNWI5ZjBiMzgyNmI2ZjJjZTBhIiwidXNlcl9pZCI6IjQifQ.SlzZ_NMZyA6abCvIFjb98OCJeDY6rEOATllwelfEknk


###

POST http://localhost:8000/orders/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY3MzM4MDY3LCJpYXQiOjE3NjczMzc3NjcsImp0aSI6IjBiYzBlNWI3NTJjZDRmNGRhMjMxZmE3MTc3YTBhOTQyIiwidXNlcl9pZCI6IjEifQ.Xz7hs98wUYD1A7Jdlc7AVgFs45oPqdbGBhIUAQPXaC4

{
   "status": "Pending",
   "user": 1,
   "items": [
      {
         "product": 4,
         "quantity": 2
      },
      {
         "product": 4,
         "quantity": 1
      }
   ]
}